config/routes.rb
Shoes::Application.routes.draw do
  root 'pages#index'
	resources :users do
		get '/following', to: 'users#following'
		get '/followers', to: 'users#followers'
		resources :pairs
		resources :follows
	end
	
	resources :photos
	post '/follows/unfollow', to: 'follows#unfollow'
	post '/follows/follow', to: 'follows#follow'
	resources :sessions, only: [:create]
	get '/login', :to => 'sessions#new'
	get '/logout', :to => 'sessions#destroy'
end

app/models/follow.rb
class Follow < ActiveRecord::Base
	validates_presence_of :follower_id, :followed_id
	validates_uniqueness_of :follower_id, :scope => :followed_id

	belongs_to :followed, class_name: 'User', primary_key: :id, foreign_key: :followed_id
	belongs_to :follower, class_name: 'User', primary_key: :id, foreign_key: :follower_id
end

app/models/pair.rb
class Pair < ActiveRecord::Base
	belongs_to :user
	has_many :photos
	
	validates_presence_of :brand
	validates_inclusion_of :condition, in: (1..10).to_a

	scope :for_sale, -> {where(available: true)}

	def thumb_url
		if !self.photos.empty?
			self.photos.first.shot_url(:thumb)
		else
			'http://cdn.niketalk.com/1/14/200x200px-ZC-14023d85_Air-Jordan-1-OG_1350815876.jpeg'
		end
	end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :pair
	mount_uploader :shot, ShotUploader

	validates_presence_of :ordinal, :pair_id
	default_scope { order('ordinal ASC') }

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
	include BCrypt
	has_many :pairs
	has_many :trackings, class_name: 'Follow', foreign_key: :followed_id, primary_key: :id
	has_many :followings, class_name: 'Follow', foreign_key: :follower_id, primary_key: :id
	has_many :followers, through: :trackings
	has_many :followeds, through: :followings

	validates_presence_of :username, :email
	validates_uniqueness_of :username, :email

  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

	def password
		@password ||= Password.new(password_hash)
  end

	def password=(new_password)
		@password = Password.create(new_password)
		self.password_hash = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def current_user
		User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def follows?(user_id)
		current_user.follows.include?(User.find(user_id))
	end
	helper_method :follows?
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	def follow
		f = Follow.where(follower_id: current_user.id, followed_id: params[:id]).first_or_create
		if request.xhr?
			render json: {}
		else
			#render json: {url: "users/#{current_user.id}/follows/?id=#{f.id}"}
			redirect_to users_path
		end
	end

	def unfollow
		f = Follow.where(follower_id: current_user.id, followed_id: params[:id])
		f.first.destroy if !f.empty?
		if request.xhr?
			render json: {}
		else
			#render json: {url: "users/#{current_user.id}/follow/?id=#{params[:id]}"}
			redirect_to users_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index

	end
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
	def index
		@user = User.find(params[:user_id])
		@pairs = @user.pairs
	end

	def new
		@user = current_user
		@pair = @user.pairs.build
	end

	def create
		@user = current_user
		@pair = current_user.pairs.build(pair_params)

		if @pair.save
			flash[:success] = 'Shoes Saved!'
			redirect_to user_pair_path(current_user, @pair)
		else
			flash[:error] = 'Your Shoes Were Not Saved'
			render 'new'
		end
	end

	def update
		@pair = Pair.find(params[:id])
		@pair.update_attributes(pair_params)
		if @pair.save
			flash[:success] = 'Shoes Updated!'
			redirect_to user_pair_path(current_user, @pair)
		else
			flash[:error] = 'Your Shoes Were Not Updated'
			render 'edit'
		end
	end

	def show
		@pair = Pair.find(params[:id])
		@main_url = main_photo(@pair)	
		@photo = Photo.new
	end

	def edit
		@user = current_user
		@pair = Pair.find(params[:id])
	end

	private
		
		def pair_params
			params.require(:pair).permit(:brand, :model, :nickname, :condition, :description)
		end

		def main_photo(pair)
			if pair.photos.count > 0
				pair.photos.first.shot_url(:main)
			else
				'http://6.kicksonfire.net/wp-content/uploads/2008/07/air-jordan-1-i-black-white-air-jordan-countdown-package-1.jpg'
			end
		end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def create
		photo = Photo.new(photo_params)
		if photo.save
			flash[:success] = 'Photo added to pair'
		else
			flash[:error] = 'Error: Photo not added'
	  end
		redirect_to user_pair_path(current_user, photo.pair)
	end

	def destroy
		photo = Photo.find(params[:id])
	
		if photo.destroy
			flash[:success] = 'Photo Deleted'
		else
			flash[:error] = 'Error: Photo not deleted'
	  end
		redirect_to edit_user_pair_path(current_user, photo.pair)
	end

	private
		def photo_params
			params.require(:photo).permit(:pair_id, :url, :ordinal, :shot)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user == nil
      flash[:error] = "User Could Not be Found"
      redirect_to login_path
    else
		  if @user.password == params[:session][:password]
				session[:user_id] = @user.id
				redirect_to @user
			else
				flash[:error] = "Username or Password is incorrect"
				redirect_to login_path
			end
	  end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.includes(:pairs)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user.password = params[:user][:password]
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user
	  else
			flash[:error] = "The Username/Password is Invalid"
			redirect_to new_user_path
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def update

	end

	def destroy

	end

	def followers
		@user = User.find(params[:user_id])
		@users = @user.followers
		render 'index'
	end

	def following
		@user = User.find(params[:user_id])
		@users = @user.followeds
		render 'index'
	end

	private
		
		def user_params
			params.require(:user).permit(:username, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
.header
  h1.title ShoeBinder
  ul
    li
      = link_to 'Connect', users_path
    -if current_user
      li
        = link_to 'Log Out', logout_path
      li
        = link_to 'My Account', user_path(current_user)
    -else
      li
        = link_to 'Log In', login_path
      li
        = link_to 'Sign Up', new_user_path

app/views/layouts/application.html.slim
doctype html
html
	head
		title Shoes
		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags
body
	= render partial: 'layouts/header'
	- flash.each do |key, value|
			= content_tag(:div, value, :class => "flash #{key}")
	= yield

app/views/pairs/_form.html.erb
<%= form_for ([@user,@pair]) do |f| %>
	<%= f.label :brand %>
	<%= f.text_field :brand %><br>
	<%= f.label :model %>
	<%= f.text_field :model %><br>
	<%= f.label :nickname %>
	<%= f.text_field :nickname %><br>
	<%= f.label :condition %>
	<%= f.number_field :condition, value: 1 %><br>
	<%= f.label :description %>
	<%= f.text_area :description, size: '30x5' %><br>
	<%= f.submit %>
<% end %>

app/views/pairs/_pair.html.erb
<table>
	<tr>
		<td><%= pair.nickname %>
	</tr>
	<tr>
		<td>
			Brand: <%= link_to pair.brand, user_pair_path(@user, pair) %> Model: <%= pair.model %>
		</td>
	</tr>
	<tr><td><%= pair.condition %>/10</td></tr>
</table>

app/views/pairs/_thumb.html.slim
.thumb
  = link_to image_tag(pair.thumb_url), user_pair_path(user, pair) 
  br
  #{pair.brand} - #{pair.model}
  =pair.nickname if pair.nickname

app/views/pairs/edit.html.erb
<%= render partial: 'form' %>

<% @pair.photos.each do |p| %>
	<%= image_tag p.shot_url(:thumb) %>
	<%= link_to 'Delete', photo_path(p), method: 'DELETE' %>
<% end %>

app/views/pairs/index.html.erb
<%= @user.username %>'s Shoes <br><br>
<% @pairs.each do |p| %>
	<%= render partial: 'pair', locals: { pair: p } %>
<% end %>

app/views/pairs/new.html.erb
<%= render partial: 'form', locals: {user: @user, pair: @pair} %>

app/views/pairs/show.html.erb
<% if current_user && current_user == @pair.user %>
	<%= form_for @photo, :html => {:multipart => true} do |f| %>
		<%= hidden_field_tag 'photo[pair_id]', @pair.id %>
		<%= f.file_field :shot %>
		<%= f.submit 'Add Photo' %>
	<% end %>
<% end %>

<%= image_tag @main_url %><br>

<table>
	<tr>
	  <% @pair.photos.each do |p| %>
			<td><%= image_tag p.shot_url(:thumb) %></td>
		<% end %>
		<%= link_to 'Edit Pair', edit_user_pair_path(current_user, @pair) if current_user && current_user == @pair.user %>
	</tr>
	<tr>
		<td>Brand</td><td><%= @pair.brand %><td>
		<td>Model</td><td><%= @pair.model %><td>
	</tr>
	<tr>
		<td>Nickname</td><td><%= @pair.nickname %></td>
		<td>Year</td><td><%= @pair.year %></td>
		<td>Condition</td><td><%= @pair.condition %>/10</td>
	</tr>
	<tr>
		<td>Description</td><td><%= @pair.description %></td>
	</tr>
	<tr>
		<td>Available?</td><td><%= @pair.available %></td>
	</tr>
</table>

app/views/users/_blurb.html.erb
<div id=<%= user.id %>>
	<%= link_to user.username, user_path(user) %><br>
	Shoes: <%= user.pairs.count %><br>
	Available For Sale: 

	<% if current_user && current_user != user %>
			<%= button_to 'Unfollow', { action: 'destroy', controller: 'follows',
					user_id: current_user.id, id: user.id }, form_class: 'unfollow' %>
			<%= button_to 'Follow', { action: 'create', controller: 'follows',
					user_id: current_user.id, id: user.id }, form_class: 'follow' %>
	<% end %>
</div>

app/views/users/_sign_up.html.erb
<%= form_for @user do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username %><br>
	<%= f.label :email %>
	<%= f.text_field :email %><br>
	<%= f.label :password %>
	<%= f.password_field :password %><br>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<div class='users'>
	<% @users.each do |u| %>
		<%= render partial: 'blurb', locals: {user: u} %><br>
	<% end %>
</div>

app/views/users/new.html.erb
<%= render partial: 'sign_up', locals: {user: @user} %>

app/views/users/show.html.slim
| #{@user.username}'s Profile
br
br
| Shoes: #{link_to @user.pairs.count, user_pairs_path(@user)}
br
| Available For Sale: #{@user.pairs.for_sale.count}
br
| Following: #{link_to @user.followeds.count, user_following_path(@user)}
br
| Followers: #{link_to @user.followers.count, user_followers_path(@user)}
br

-if current_user && current_user != @user
	= button_to 'Unfollow', { action: 'unfollow', controller: 'follows'},
				form_class: 'unfollow'
	= button_to 'Follow', { action: 'create', controller: 'follows',
				user_id: current_user.id, id: @user.id }, form_class: 'follow'
br
= link_to 'Add Shoes', new_user_pair_path(:user_id => current_user.id) if @user == current_user 
br
.gallery
  -@user.pairs.each do |p|
    -	if p.thumb_url
      =render partial: 'pairs/thumb', locals: {pair: p, user: @user}	